apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  namespace: edu-denis-turishchev
spec:
  schedule: "0 3 * * 1"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      ttlSecondsAfterFinished: 100
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-clearsession-job
            image: 1ns0mn1a7/django-app:latest
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py",  "clearsessions"]
            envFrom:
              - secretRef:
                  name: django-secrets
