apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: edu-denis-turishchev
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate-job
        image: 1ns0mn1a7/django-app:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "manage.py",  "migrate", "--no-input"]
        envFrom:
          - secretRef:
              name: django-secrets